on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install  # Replace with your build command if necessary
      - name: Build and deploy to GitHub Pages
        run: |
          npm run build  # Replace with your build command
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git checkout gh-pages  # Change to the branch you want to deploy to
          mv -f build/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages  # Change to your branch name












